[2024-06-01T15:34:18.394+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: etl_dag.transform scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2024-06-01T15:34:18.453+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: etl_dag.transform scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2024-06-01T15:34:18.459+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-06-01T15:34:18.460+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2024-06-01T15:34:18.491+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-06-01T15:34:18.663+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): transform> on 2023-01-01 00:00:00+00:00
[2024-06-01T15:34:18.772+0000] {standard_task_runner.py:55} INFO - Started process 383 to run task
[2024-06-01T15:34:18.830+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'transform', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpztev3wmo']
[2024-06-01T15:34:18.855+0000] {standard_task_runner.py:83} INFO - Job 35: Subtask transform
[2024-06-01T15:34:19.754+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-01T15:34:20.405+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:121 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-01T15:34:20.993+0000] {task_command.py:389} INFO - Running <TaskInstance: etl_dag.transform scheduled__2023-01-01T00:00:00+00:00 [running]> on host c5b738fed888
[2024-06-01T15:34:21.643+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_dag
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2023-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-01T00:00:00+00:00
[2024-06-01T15:34:21.917+0000] {python.py:177} INFO - Done. Returned value was:    column1                   column2
0        1             100 phần trăm
1        2  20 xuân này, 20 xuân sau
2        3            40 năm gặp lại
3        4           60 năm cuộc đời
4        5                  70 lần 7
..     ...                       ...
95      96    Ánh mắt Chúa trong đời
96      97           Ánh mắt con thơ
97      98            Anh mong có em
98      99                  Anh muốn
99     100      Anh muốn em sống sao

[100 rows x 2 columns]
[2024-06-01T15:34:21.978+0000] {xcom.py:635} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-06-01T15:34:21.983+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2301, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 170, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2024-06-01T15:34:22.016+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=etl_dag, task_id=transform, execution_date=20230101T000000, start_date=20240601T153418, end_date=20240601T153422
[2024-06-01T15:34:22.045+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 35 for task transform (Object of type DataFrame is not JSON serializable; 383)
[2024-06-01T15:34:22.105+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-06-01T15:34:22.213+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
